# Generated by Django 5.1.1 on 2024-09-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_actors_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='films.filmlist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actors',
            name='name',
            field=models.TextField(),
        ),
    ]
