# Generated by Django 5.1.1 on 2024-09-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_actors_film_alter_actors_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actors',
            name='film',
        ),
    ]
